name: Hello world with python
run-name: Learning github actions
on: ['push']
jobs:
  hello-world:
   runs-on: ubuntu-latest
   steps:
    - name: Clone repo
      uses: actions/checkout@v3
	- name: Set variable
	  run: echo "USERNAME=${{github.actor}}" >> $GITHUB_ENV
	- name: run script
	  run: python hello-python.py 
