name: Vars and secrets
run-name: Running var and secrets

on:
  workflow_dispatch
env:
  name: 'Juanito Devops'
jobs:
  show-secret:
    if: ${{github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest
    steps:
      - name: Running local and secret vars
        run: echo ${{env.name}} and password is ${{secrets.PASSWORD}}
        
  
